DEFAULT_FLAVOR_NAME = "ds512M"
DEFAULT_NETWORK_LABEL = "private"
DEFAULT_IMAGE_NAME = "ubuntu"
DEFAULT_SEC_GROUP_NAME = "default"

OC_SERVICE_PORT = 5003
LOG_COLLECTOR_ADDRESS = 'http://10.0.0.25:5004/log-collector/append'
